[package]
name = "aoc2019"
version = "0.1.0"
edition = "2021"

[lib]
name = "aoc"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
num = "0.4.1"
